import Head from 'next/head';
import { Header } from '@/components/Header';
import { ReactNode } from 'react';

const Layout = ({ children }: { children?: ReactNode }) => {
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="h-screen w-screen flex flex-col p-5">
        <Header />
        {children}
      </main>
    </div>
  );
};

export default Layout;
