import Head from 'next/head';
import { Header } from '@/components/Header';
import { useConfig } from '@/hooks/useConfig';
import { useDebugPanel } from '@/contexts/DebugPanel';
import { classNames } from '@/util';
import { ReactNode } from 'react';

const Layout = ({ children }: { children?: ReactNode }) => {
  const { showDebug } = useConfig();
  const { setIsOpen } = useDebugPanel();

  return (
    <>
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <main className="min-h-screen flex flex-col relative p-5 w-full items-center">
        <Header />
        {children}
        <div className={classNames('mb-6', showDebug ? 'self-start' : 'hidden')}>
          <button
            type="button"
            className="rounded bg-white px-2 py-1 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 ml-2 self-center"
            onClick={() => setIsOpen(true)}
          >
            Debug
          </button>
        </div>
      </main>
    </>
  );
};

export default Layout;
