name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn install
      - name: Build frontend
        run: yarn run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn install
      - name: Build frontend
        run: yarn run lint
